version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: anoq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: anoq_db
      POSTGRES_USER: anoq_user
      POSTGRES_PASSWORD: anoq_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./go-backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anoq_user -d anoq_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go backend service (will be added later)
  # backend:
  #   build:
  #     context: ./go-backend
  #     dockerfile: Dockerfile
  #   container_name: anoq_backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=anoq_db
  #     - DB_USER=anoq_user
  #     - DB_PASSWORD=anoq_password

volumes:
  postgres_data: 