version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=anoq
      - AUTH_TOKEN=dev-token
    volumes:
      - .:/app
    networks:
      - anoq-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anoq
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount migrations directory for init scripts
      - ./server/migrations:/docker-entrypoint-initdb.d
    networks:
      - anoq-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:


networks:
  anoq-network:
    driver: bridge
